const quotes = [
  "Do one thing every day that scares you. – Eleanor Roosevelt",
  "The best way to predict the future is to create it. – Peter Drucker",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "Don’t wait for opportunity. Create it. – Unknown",
  "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
  "Happiness is not something ready made. It comes from your own actions. – Dalai Lama",
  "It always seems impossible until it's done. – Nelson Mandela",
  "What we think, we become. – Buddha",
  "Dream big and dare to fail. – Norman Vaughan",
  "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
  "Life is what happens when you’re busy making other plans. – John Lennon",
  "In the middle of difficulty lies opportunity. – Albert Einstein",
  "The only way to do great work is to love what you do. – Steve Jobs",
  "The mind is everything. What you think you become. – Buddha",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. – Joshua J. Marine",
  "I am not a product of my circumstances. I am a product of my decisions. – Stephen Covey",
  "You miss 100% of the shots you don’t take. – Wayne Gretzky",
  "Whether you think you can or you think you can’t, you’re right. – Henry Ford",
  "We become what we think about. – Earl Nightingale",
  "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
  "I would rather die of passion than of boredom. – Vincent van Gogh",
  "The best revenge is massive success. – Frank Sinatra",
  "The harder I work, the luckier I get. – Gary Player",
  "It’s not whether you get knocked down; it’s whether you get up. – Vince Lombardi",
  "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "The purpose of our lives is to be happy. – Dalai Lama",
  "Life is really simple, but we insist on making it complicated. – Confucius",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "Don't be afraid to give up the good to go for the great. – John D. Rockefeller",
  "I have not failed. I've just found 10,000 ways that won't work. – Thomas Edison",
  "Action is the foundational key to all success. – Pablo Picasso",
  "Opportunities don't happen, you create them. – Chris Grosser",
  "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
  "You must be the change you wish to see in the world. – Mahatma Gandhi",
  "Your time is limited, don't waste it living someone else's life. – Steve Jobs",
  "Every moment is a fresh beginning. – T.S. Eliot",
  "Life is 10% what happens to me and 90% how I react to it. – Charles R. Swindoll",
  "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
  "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
  "The road to success and the road to failure are almost exactly the same. – Colin R. Davis",
  "It does not matter how slowly you go, so long as you do not stop. – Confucius",
  "Doubt kills more dreams than failure ever will. – Suzy Kassem",
  "Life is what happens when you're busy making other plans. – Allen Saunders",
  "You only live once, but if you do it right, once is enough. – Mae West",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
  "Don’t judge each day by the harvest you reap but by the seeds that you plant. – Robert Louis Stevenson",
  "It always seems impossible until it's done. – Nelson Mandela",
  "To succeed in life, you need two things: ignorance and confidence. – Mark Twain",
  "Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats",
  "The biggest adventure you can take is to live the life of your dreams. – Oprah Winfrey",
  "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination. – Jimmy Dean",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "The only impossible journey is the one you never begin. – Tony Robbins",
  "The best way to get started is to quit talking and begin doing. – Walt Disney",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
  "You get what you give. – Jennifer Lopez",
  "Turn your wounds into wisdom. – Oprah Winfrey",
  "The journey of a thousand miles begins with one step. – Lao Tzu",
  "If you want to lift yourself up, lift up someone else. – Booker T. Washington",
  "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
  "You define your own life. Don’t let other people write your script. – Oprah Winfrey",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. – Nelson Mandela",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
  "Be yourself; everyone else is already taken. – Oscar Wilde",
  "I have learned over the years that when one's mind is made up, this diminishes fear. – Rosa Parks",
  "It’s not the years in your life that count. It’s the life in your years. – Abraham Lincoln",
  "Our lives begin to end the day we become silent about things that matter. – Martin Luther King Jr.",
  "Life isn’t about finding yourself. Life is about creating yourself. – George Bernard Shaw",
  "Great things are done by a series of small things brought together. – Vincent Van Gogh",
  "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
  "I attribute my success to this: I never gave or took any excuse. – Florence Nightingale",
  "If you can dream it, you can do it. – Walt Disney",
  "No one can make you feel inferior without your consent. – Eleanor Roosevelt",
  "Difficulties in life are intended to make us better, not bitter. – Dan Reeves",
  "Don’t let the fear of losing be greater than the excitement of winning. – Robert Kiyosaki",
  "It's not what you achieve, it's what you overcome. That's what defines your career. – Carlton Fisk",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure. – Colin Powell",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. – Winston Churchill",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "The best preparation for tomorrow is doing your best today. – H. Jackson Brown, Jr.",
  "The more you praise and celebrate your life, the more there is in life to celebrate. – Oprah Winfrey",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill",
  "Success is not in what you have, but who you are. – Bo Bennett",
  "The best way out is always through. – Robert Frost",
  "Do what you can, with what you have, where you are. – Theodore Roosevelt",
  "You have power over your mind—not outside events. Realize this, and you will find strength. – Marcus Aurelius",
  "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
  "It’s not about ideas. It’s about making ideas happen. – Scott Belsky",
  "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
  "Do not be embarrassed by your failures, learn from them and start again. – Richard Branson",
  "If you want to live a happy life, tie it to a goal, not to people or things. – Albert Einstein",
  "Don’t cry because it’s over, smile because it happened. – Dr. Seuss",
  "Failure is simply the opportunity to begin again, this time more intelligently. – Henry Ford",
  "If you tell the truth, you don't have to remember anything. – Mark Twain",
  "In three words I can sum up everything I've learned about life: it goes on. – Robert Frost",
  "Life isn't about waiting for the storm to pass, it's about learning how to dance in the rain. – Vivian Greene",
  "Do what is right, not what is easy nor what is popular. – Roy T. Bennett",
  "You don't always need a plan. Sometimes you just need to breathe, trust, let go, and see what happens. – Mandy Hale",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. – Ralph Waldo Emerson",
  "Your life does not get better by chance, it gets better by change. – Jim Rohn",
  "Doubt kills more dreams than failure ever will. – Suzy Kassem",
  "Success is how high you bounce when you hit bottom. – George S. Patton",
  "It is during our darkest moments that we must focus to see the light. – Aristotle",
  "Never let the fear of striking out keep you from playing the game. – Babe Ruth",
  "The greatest discovery of all time is that a person can change their future by merely changing their attitude. – Oprah Winfrey",
  "Success is liking yourself, liking what you do, and liking how you do it. – Maya Angelou",
  "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
  "It’s not the load that breaks you down, it’s the way you carry it. – Lou Holtz",
  "Every strike brings me closer to the next home run. – Babe Ruth",
  "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless. – Jamie Paolinetti",
  "You can, you should, and if you’re brave enough to start, you will. – Stephen King",
  "The way I see it, if you want the rainbow, you gotta put up with the rain. – Dolly Parton",
  "The best way to cheer yourself is to try to cheer someone else up. – Mark Twain",
  "Fall seven times, stand up eight. – Japanese Proverb",
  "Everything you can imagine is real. – Pablo Picasso",
  "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
  "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us. – Helen Keller",
  "Don't let yesterday take up too much of today. – Will Rogers",
  "It does not matter how slowly you go as long as you do not stop. – Confucius",
  "You will face many defeats in life, but never let yourself be defeated. – Maya Angelou",
  "A person who never made a mistake never tried anything new. – Albert Einstein",
  "You can never cross the ocean until you have the courage to lose sight of the shore. – Christopher Columbus",
  "Our lives begin to end the day we become silent about things that matter. – Martin Luther King Jr.",
  "The more you dream, the farther you get. – Michael Phelps",
  "Strive not to be a success, but rather to be of value. – Albert Einstein",
  "Don’t count the days, make the days count. – Muhammad Ali",
  "If you don't stand for something, you will fall for anything. – Gordon A. Eadie",
  "Too many of us are not living our dreams because we are living our fears. – Les Brown",
  "We may encounter many defeats, but we must not be defeated. – Maya Angelou",
  "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
  "Don't judge each day by the harvest you reap but by the seeds that you plant. – Robert Louis Stevenson",
  "Success isn’t about how your life looks to others, it’s about how it feels to you. – Michelle Obama",
  "The only way to do great work is to love what you do. – Steve Jobs",
  "You miss 100% of the shots you don’t take. – Wayne Gretzky",
  "It’s hard to beat a person who never gives up. – Babe Ruth",
  "If you are not willing to risk the usual, you will have to settle for the ordinary. – Jim Rohn",
  "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
  "What we achieve inwardly will change outer reality. – Plutarch",
  "There is no substitute for hard work. – Thomas Edison",
  "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "Don’t wait. The time will never be just right. – Napoleon Hill",
  "Whether you think you can or you think you can’t, you’re right. – Henry Ford",
  "Act as if what you do makes a difference. It does. – William James",
  "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Courage is grace under pressure. – Ernest Hemingway",
  "I attribute my success to this: I never gave or took any excuse. – Florence Nightingale",
  "If you want to achieve greatness stop asking for permission. – Anonymous",
  "No one can make you feel inferior without your consent. – Eleanor Roosevelt",
  "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. – William James",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "People who are crazy enough to think they can change the world, are the ones who do. – Rob Siltanen",
  "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit. – Conrad Hilton",
  "Try not to become a man of success, but rather become a man of value. – Albert Einstein",
  "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. – Henry Ford",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. – Eleanor Roosevelt",
  "Opportunities don’t happen. You create them. – Chris Grosser",
  "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson",
  "Good things come to people who wait, but better things come to those who go out and get them. – Anonymous",
  "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. – Dale Carnegie",
  "Whenever you find yourself on the side of the majority, it is time to pause and reflect. – Mark Twain",
  "Don’t raise your voice, improve your argument. – Anonymous",
  "You can’t use up creativity. The more you use, the more you have. – Maya Angelou",
  "A man who dares to waste one hour of time has not discovered the value of life. – Charles Darwin",
  "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds. – Orison Swett Marden",
  "If you can dream it, you can do it. – Walt Disney",
  "The successful warrior is the average man, with laser-like focus. – Bruce Lee",
  "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy. – Norman Vincent Peale",
];

const text = document.getElementById("txt");

function randomQuote() {
  randomColor();
  const a = Math.floor(Math.random() * quotes.length);
  text.innerHTML = `${quotes[a]}`;
}

function randomColor() {
  const red = Math.round(Math.random() * 255);
  const green = Math.round(Math.random() * 255);
  const blue = Math.round(Math.random() * 255);

  const color = `rgb(${red},${green},${blue})`;

  document.body.style.backgroundColor = color;
}
